[project]
name = "mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.6.0",
    "aiohttp>=3.11.18",
    "mcp>=1.6.0",
    "nest-asyncio>=1.6.0",
    "torch>=2.7.0",
    "transformers>=4.51.3",
]
